Repository voluntarily/vly2, pull requests merged in 2019-11, with the labels that each got.

#460 VP-810 - restore default mongodb url
  x/db/migrateTagsToStrings.js
Labels: hotfix

#458 VP-804 Local build broken when language set to Chinese simplified
  server/server.js
Labels: bug

#483 protect goal schema
  server/api/goal/goal.js
Labels: bug, hotfix
