Repository voluntarily/vly2, pull requests merged in 2019-09, with the labels that each got.

#358 Updated contributor list
  CONTRIBUTORS
Labels: Name

#361 Vp 82 santhosh
  CONTRIBUTORS
Labels: Name

#362 Fixed Styling on error 500 page. Changed from h1 to h2, for error tex…
  __tests__/404.spec.js
  pages/_error.js
Labels: bug

#371 Added Dom
  CONTRIBUTORS
Labels: Name

#378 VP462 Shield Site
  components/Footer/Footer.js
  components/Footer/WomensRefuge.js
  components/Footer/__tests__/WomensRefuge.spec.js
  components/__tests__/Footer.spec.js
  package-lock.json
  pages/_document.js
  static/womens_refuge.png
Labels: enhancement

#381 Vp 236 order or group volunteer
  components/Interest/InterestTable.js
  components/Interest/__tests__/InterestTable.spec.js
Labels: enhancement
